
GET https://quiet-surf-6831.fly.dev/api/persons/64849fe253196b4f2bce3945

###
POST https://quiet-surf-6831.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Trial Error",
    "number": "0123456789"
}